<div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
  <div class="bg-dark p-4">
    <h5 class="text-body-emphasis h4">Data<strong> Sensor</strong></h5>
    <span class="text-body-secondary">Toggleable via the navbar brand.</span>
    <ul class="navbar-nav mt-3">
      <li class="nav-item">
        <a class="nav-link active text-white" aria-current="page" href="index.php">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="tabel.php">Tabel</a>
      </li>
    </ul>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark shadow-sm py-4">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
